--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create gaming_hud_bottom_role_layer
local gaming_hud_bottom_role_layer=cc.Node:create()
gaming_hud_bottom_role_layer:setName("gaming_hud_bottom_role_layer")
layout = ccui.LayoutComponent:bindLayoutComponent(gaming_hud_bottom_role_layer)
layout:setSize({width = 800.0000, height = 300.0000})

--Create role_head_sprite
local role_head_sprite = cc.Sprite:create("ui/gaming/hud/png/role_head.png")
role_head_sprite:setName("role_head_sprite")
role_head_sprite:setTag(12)
role_head_sprite:setCascadeColorEnabled(true)
role_head_sprite:setCascadeOpacityEnabled(true)
role_head_sprite:setPosition(155.7453, 178.7100)
role_head_sprite:setScaleX(0.4492)
role_head_sprite:setScaleY(0.2978)
layout = ccui.LayoutComponent:bindLayoutComponent(role_head_sprite)
layout:setPositionPercentX(0.1947)
layout:setPositionPercentY(0.5957)
layout:setPercentWidth(0.6037)
layout:setPercentHeight(2.3533)
layout:setSize({width = 483.0000, height = 706.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(-85.7547)
layout:setRightMargin(402.7547)
layout:setTopMargin(-231.7100)
layout:setBottomMargin(-174.2900)
role_head_sprite:setBlendFunc({src = 1, dst = 771})
gaming_hud_bottom_role_layer:addChild(role_head_sprite)

--Create role_name_text
local role_name_text = ccui.Text:create()
role_name_text:ignoreContentAdaptWithSize(true)
role_name_text:setTextAreaSize({width = 0, height = 0})
role_name_text:setFontSize(20)
role_name_text:setString([[role_name]])
role_name_text:setLayoutComponentEnabled(true)
role_name_text:setName("role_name_text")
role_name_text:setTag(13)
role_name_text:setCascadeColorEnabled(true)
role_name_text:setCascadeOpacityEnabled(true)
role_name_text:setPosition(147.2151, 40.3117)
role_name_text:setScaleX(1.9817)
role_name_text:setScaleY(2.3385)
layout = ccui.LayoutComponent:bindLayoutComponent(role_name_text)
layout:setPositionPercentX(0.1840)
layout:setPositionPercentY(0.1344)
layout:setPercentWidth(0.1125)
layout:setPercentHeight(0.0667)
layout:setSize({width = 90.0000, height = 20.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(1)
layout:setLeftMargin(102.2151)
layout:setRightMargin(607.7849)
layout:setTopMargin(249.6883)
layout:setBottomMargin(30.3117)
gaming_hud_bottom_role_layer:addChild(role_name_text)

--Create role_blood_loadingbar
local role_blood_loadingbar = ccui.LoadingBar:create()
role_blood_loadingbar:loadTexture("ui/gaming/hud/png/blood_blue.png",0)
role_blood_loadingbar:ignoreContentAdaptWithSize(false)
role_blood_loadingbar:setPercent(80)
role_blood_loadingbar:setLayoutComponentEnabled(true)
role_blood_loadingbar:setName("role_blood_loadingbar")
role_blood_loadingbar:setTag(15)
role_blood_loadingbar:setCascadeColorEnabled(true)
role_blood_loadingbar:setCascadeOpacityEnabled(true)
role_blood_loadingbar:setPosition(547.2137, 228.3444)
role_blood_loadingbar:setScaleX(2.2295)
role_blood_loadingbar:setScaleY(3.0623)
layout = ccui.LayoutComponent:bindLayoutComponent(role_blood_loadingbar)
layout:setPositionPercentX(0.6840)
layout:setPositionPercentY(0.7611)
layout:setPercentWidth(0.2338)
layout:setPercentHeight(0.0633)
layout:setSize({width = 187.0000, height = 19.0000})
layout:setLeftMargin(453.7137)
layout:setRightMargin(159.2863)
layout:setTopMargin(62.1556)
layout:setBottomMargin(218.8444)
gaming_hud_bottom_role_layer:addChild(role_blood_loadingbar)

--Create role_power_loadingbar
local role_power_loadingbar = ccui.LoadingBar:create()
role_power_loadingbar:loadTexture("ui/gaming/hud/png/blood_blue.png",0)
role_power_loadingbar:ignoreContentAdaptWithSize(false)
role_power_loadingbar:setPercent(80)
role_power_loadingbar:setLayoutComponentEnabled(true)
role_power_loadingbar:setName("role_power_loadingbar")
role_power_loadingbar:setTag(16)
role_power_loadingbar:setCascadeColorEnabled(true)
role_power_loadingbar:setCascadeOpacityEnabled(true)
role_power_loadingbar:setPosition(547.2101, 145.9225)
role_power_loadingbar:setScaleX(2.2295)
role_power_loadingbar:setScaleY(2.9201)
layout = ccui.LayoutComponent:bindLayoutComponent(role_power_loadingbar)
layout:setPositionPercentX(0.6840)
layout:setPositionPercentY(0.4864)
layout:setPercentWidth(0.2338)
layout:setPercentHeight(0.0633)
layout:setSize({width = 187.0000, height = 19.0000})
layout:setLeftMargin(453.7101)
layout:setRightMargin(159.2899)
layout:setTopMargin(144.5775)
layout:setBottomMargin(136.4225)
gaming_hud_bottom_role_layer:addChild(role_power_loadingbar)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = gaming_hud_bottom_role_layer
return result;
end

return Result

