// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actor_type_cfg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "actor_type_cfg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gamer {
namespace cfg {

namespace {

const ::google::protobuf::EnumDescriptor* ActorTypes_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_actor_5ftype_5fcfg_2eproto() {
  protobuf_AddDesc_actor_5ftype_5fcfg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "actor_type_cfg.proto");
  GOOGLE_CHECK(file != NULL);
  ActorTypes_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_actor_5ftype_5fcfg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_actor_5ftype_5fcfg_2eproto() {
}

void protobuf_AddDesc_actor_5ftype_5fcfg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024actor_type_cfg.proto\022\tgamer.cfg*O\n\nAct"
    "orTypes\022\025\n\021ACTOR_HERO_KNIGHT\020\000\022\025\n\021ACTOR_"
    "HERO_ARCHER\020\001\022\023\n\017ACTOR_HERO_MAGE\020\002", 114);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "actor_type_cfg.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_actor_5ftype_5fcfg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_actor_5ftype_5fcfg_2eproto {
  StaticDescriptorInitializer_actor_5ftype_5fcfg_2eproto() {
    protobuf_AddDesc_actor_5ftype_5fcfg_2eproto();
  }
} static_descriptor_initializer_actor_5ftype_5fcfg_2eproto_;
const ::google::protobuf::EnumDescriptor* ActorTypes_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ActorTypes_descriptor_;
}
bool ActorTypes_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cfg
}  // namespace gamer

// @@protoc_insertion_point(global_scope)
