// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camera_cfg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "camera_cfg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gamer {
namespace cfg {

namespace {

const ::google::protobuf::Descriptor* CameraCfg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CameraCfg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_camera_5fcfg_2eproto() {
  protobuf_AddDesc_camera_5fcfg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "camera_cfg.proto");
  GOOGLE_CHECK(file != NULL);
  CameraCfg_descriptor_ = file->message_type(0);
  static const int CameraCfg_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraCfg, camera_pos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraCfg, camera_lookat_),
  };
  CameraCfg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CameraCfg_descriptor_,
      CameraCfg::default_instance_,
      CameraCfg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraCfg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CameraCfg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CameraCfg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_camera_5fcfg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CameraCfg_descriptor_, &CameraCfg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_camera_5fcfg_2eproto() {
  delete CameraCfg::default_instance_;
  delete CameraCfg_reflection_;
}

void protobuf_AddDesc_camera_5fcfg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gamer::cfg::protobuf_AddDesc_common_5fcfg_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020camera_cfg.proto\022\tgamer.cfg\032\020common_cf"
    "g.proto\"X\n\tCameraCfg\022#\n\ncamera_pos\030\001 \002(\013"
    "2\017.gamer.cfg.Vec3\022&\n\rcamera_lookat\030\002 \002(\013"
    "2\017.gamer.cfg.Vec3", 137);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "camera_cfg.proto", &protobuf_RegisterTypes);
  CameraCfg::default_instance_ = new CameraCfg();
  CameraCfg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_camera_5fcfg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_camera_5fcfg_2eproto {
  StaticDescriptorInitializer_camera_5fcfg_2eproto() {
    protobuf_AddDesc_camera_5fcfg_2eproto();
  }
} static_descriptor_initializer_camera_5fcfg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CameraCfg::kCameraPosFieldNumber;
const int CameraCfg::kCameraLookatFieldNumber;
#endif  // !_MSC_VER

CameraCfg::CameraCfg()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gamer.cfg.CameraCfg)
}

void CameraCfg::InitAsDefaultInstance() {
  camera_pos_ = const_cast< ::gamer::cfg::Vec3*>(&::gamer::cfg::Vec3::default_instance());
  camera_lookat_ = const_cast< ::gamer::cfg::Vec3*>(&::gamer::cfg::Vec3::default_instance());
}

CameraCfg::CameraCfg(const CameraCfg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gamer.cfg.CameraCfg)
}

void CameraCfg::SharedCtor() {
  _cached_size_ = 0;
  camera_pos_ = NULL;
  camera_lookat_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CameraCfg::~CameraCfg() {
  // @@protoc_insertion_point(destructor:gamer.cfg.CameraCfg)
  SharedDtor();
}

void CameraCfg::SharedDtor() {
  if (this != default_instance_) {
    delete camera_pos_;
    delete camera_lookat_;
  }
}

void CameraCfg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CameraCfg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CameraCfg_descriptor_;
}

const CameraCfg& CameraCfg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_camera_5fcfg_2eproto();
  return *default_instance_;
}

CameraCfg* CameraCfg::default_instance_ = NULL;

CameraCfg* CameraCfg::New() const {
  return new CameraCfg;
}

void CameraCfg::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_camera_pos()) {
      if (camera_pos_ != NULL) camera_pos_->::gamer::cfg::Vec3::Clear();
    }
    if (has_camera_lookat()) {
      if (camera_lookat_ != NULL) camera_lookat_->::gamer::cfg::Vec3::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CameraCfg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gamer.cfg.CameraCfg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gamer.cfg.Vec3 camera_pos = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_camera_pos()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_camera_lookat;
        break;
      }

      // required .gamer.cfg.Vec3 camera_lookat = 2;
      case 2: {
        if (tag == 18) {
         parse_camera_lookat:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_camera_lookat()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gamer.cfg.CameraCfg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gamer.cfg.CameraCfg)
  return false;
#undef DO_
}

void CameraCfg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gamer.cfg.CameraCfg)
  // required .gamer.cfg.Vec3 camera_pos = 1;
  if (has_camera_pos()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->camera_pos(), output);
  }

  // required .gamer.cfg.Vec3 camera_lookat = 2;
  if (has_camera_lookat()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->camera_lookat(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gamer.cfg.CameraCfg)
}

::google::protobuf::uint8* CameraCfg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gamer.cfg.CameraCfg)
  // required .gamer.cfg.Vec3 camera_pos = 1;
  if (has_camera_pos()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->camera_pos(), target);
  }

  // required .gamer.cfg.Vec3 camera_lookat = 2;
  if (has_camera_lookat()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->camera_lookat(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gamer.cfg.CameraCfg)
  return target;
}

int CameraCfg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .gamer.cfg.Vec3 camera_pos = 1;
    if (has_camera_pos()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->camera_pos());
    }

    // required .gamer.cfg.Vec3 camera_lookat = 2;
    if (has_camera_lookat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->camera_lookat());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CameraCfg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CameraCfg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CameraCfg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CameraCfg::MergeFrom(const CameraCfg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_camera_pos()) {
      mutable_camera_pos()->::gamer::cfg::Vec3::MergeFrom(from.camera_pos());
    }
    if (from.has_camera_lookat()) {
      mutable_camera_lookat()->::gamer::cfg::Vec3::MergeFrom(from.camera_lookat());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CameraCfg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraCfg::CopyFrom(const CameraCfg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraCfg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_camera_pos()) {
    if (!this->camera_pos().IsInitialized()) return false;
  }
  if (has_camera_lookat()) {
    if (!this->camera_lookat().IsInitialized()) return false;
  }
  return true;
}

void CameraCfg::Swap(CameraCfg* other) {
  if (other != this) {
    std::swap(camera_pos_, other->camera_pos_);
    std::swap(camera_lookat_, other->camera_lookat_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CameraCfg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CameraCfg_descriptor_;
  metadata.reflection = CameraCfg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cfg
}  // namespace gamer

// @@protoc_insertion_point(global_scope)
