// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: space_cfg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "space_cfg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gamer {
namespace cfg {

namespace {

const ::google::protobuf::Descriptor* SpaceCfg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SpaceCfg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_space_5fcfg_2eproto() {
  protobuf_AddDesc_space_5fcfg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "space_cfg.proto");
  GOOGLE_CHECK(file != NULL);
  SpaceCfg_descriptor_ = file->message_type(0);
  static const int SpaceCfg_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpaceCfg, space_ori_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpaceCfg, space_size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpaceCfg, space_box_num_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpaceCfg, space_cell_num_),
  };
  SpaceCfg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SpaceCfg_descriptor_,
      SpaceCfg::default_instance_,
      SpaceCfg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpaceCfg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SpaceCfg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SpaceCfg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_space_5fcfg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SpaceCfg_descriptor_, &SpaceCfg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_space_5fcfg_2eproto() {
  delete SpaceCfg::default_instance_;
  delete SpaceCfg_reflection_;
}

void protobuf_AddDesc_space_5fcfg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gamer::cfg::protobuf_AddDesc_common_5fcfg_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017space_cfg.proto\022\tgamer.cfg\032\020common_cfg"
    ".proto\"\244\001\n\010SpaceCfg\022\"\n\tspace_ori\030\001 \002(\0132\017"
    ".gamer.cfg.Vec3\022#\n\nspace_size\030\002 \002(\0132\017.ga"
    "mer.cfg.Vec3\022&\n\rspace_box_num\030\003 \002(\0132\017.ga"
    "mer.cfg.Vec3\022\'\n\016space_cell_num\030\004 \002(\0132\017.g"
    "amer.cfg.Vec3", 213);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "space_cfg.proto", &protobuf_RegisterTypes);
  SpaceCfg::default_instance_ = new SpaceCfg();
  SpaceCfg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_space_5fcfg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_space_5fcfg_2eproto {
  StaticDescriptorInitializer_space_5fcfg_2eproto() {
    protobuf_AddDesc_space_5fcfg_2eproto();
  }
} static_descriptor_initializer_space_5fcfg_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int SpaceCfg::kSpaceOriFieldNumber;
const int SpaceCfg::kSpaceSizeFieldNumber;
const int SpaceCfg::kSpaceBoxNumFieldNumber;
const int SpaceCfg::kSpaceCellNumFieldNumber;
#endif  // !_MSC_VER

SpaceCfg::SpaceCfg()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gamer.cfg.SpaceCfg)
}

void SpaceCfg::InitAsDefaultInstance() {
  space_ori_ = const_cast< ::gamer::cfg::Vec3*>(&::gamer::cfg::Vec3::default_instance());
  space_size_ = const_cast< ::gamer::cfg::Vec3*>(&::gamer::cfg::Vec3::default_instance());
  space_box_num_ = const_cast< ::gamer::cfg::Vec3*>(&::gamer::cfg::Vec3::default_instance());
  space_cell_num_ = const_cast< ::gamer::cfg::Vec3*>(&::gamer::cfg::Vec3::default_instance());
}

SpaceCfg::SpaceCfg(const SpaceCfg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gamer.cfg.SpaceCfg)
}

void SpaceCfg::SharedCtor() {
  _cached_size_ = 0;
  space_ori_ = NULL;
  space_size_ = NULL;
  space_box_num_ = NULL;
  space_cell_num_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SpaceCfg::~SpaceCfg() {
  // @@protoc_insertion_point(destructor:gamer.cfg.SpaceCfg)
  SharedDtor();
}

void SpaceCfg::SharedDtor() {
  if (this != default_instance_) {
    delete space_ori_;
    delete space_size_;
    delete space_box_num_;
    delete space_cell_num_;
  }
}

void SpaceCfg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SpaceCfg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SpaceCfg_descriptor_;
}

const SpaceCfg& SpaceCfg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_space_5fcfg_2eproto();
  return *default_instance_;
}

SpaceCfg* SpaceCfg::default_instance_ = NULL;

SpaceCfg* SpaceCfg::New() const {
  return new SpaceCfg;
}

void SpaceCfg::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    if (has_space_ori()) {
      if (space_ori_ != NULL) space_ori_->::gamer::cfg::Vec3::Clear();
    }
    if (has_space_size()) {
      if (space_size_ != NULL) space_size_->::gamer::cfg::Vec3::Clear();
    }
    if (has_space_box_num()) {
      if (space_box_num_ != NULL) space_box_num_->::gamer::cfg::Vec3::Clear();
    }
    if (has_space_cell_num()) {
      if (space_cell_num_ != NULL) space_cell_num_->::gamer::cfg::Vec3::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SpaceCfg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gamer.cfg.SpaceCfg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gamer.cfg.Vec3 space_ori = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_space_ori()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_space_size;
        break;
      }

      // required .gamer.cfg.Vec3 space_size = 2;
      case 2: {
        if (tag == 18) {
         parse_space_size:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_space_size()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_space_box_num;
        break;
      }

      // required .gamer.cfg.Vec3 space_box_num = 3;
      case 3: {
        if (tag == 26) {
         parse_space_box_num:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_space_box_num()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_space_cell_num;
        break;
      }

      // required .gamer.cfg.Vec3 space_cell_num = 4;
      case 4: {
        if (tag == 34) {
         parse_space_cell_num:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_space_cell_num()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gamer.cfg.SpaceCfg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gamer.cfg.SpaceCfg)
  return false;
#undef DO_
}

void SpaceCfg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gamer.cfg.SpaceCfg)
  // required .gamer.cfg.Vec3 space_ori = 1;
  if (has_space_ori()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->space_ori(), output);
  }

  // required .gamer.cfg.Vec3 space_size = 2;
  if (has_space_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->space_size(), output);
  }

  // required .gamer.cfg.Vec3 space_box_num = 3;
  if (has_space_box_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->space_box_num(), output);
  }

  // required .gamer.cfg.Vec3 space_cell_num = 4;
  if (has_space_cell_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->space_cell_num(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gamer.cfg.SpaceCfg)
}

::google::protobuf::uint8* SpaceCfg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gamer.cfg.SpaceCfg)
  // required .gamer.cfg.Vec3 space_ori = 1;
  if (has_space_ori()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->space_ori(), target);
  }

  // required .gamer.cfg.Vec3 space_size = 2;
  if (has_space_size()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->space_size(), target);
  }

  // required .gamer.cfg.Vec3 space_box_num = 3;
  if (has_space_box_num()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->space_box_num(), target);
  }

  // required .gamer.cfg.Vec3 space_cell_num = 4;
  if (has_space_cell_num()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->space_cell_num(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gamer.cfg.SpaceCfg)
  return target;
}

int SpaceCfg::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .gamer.cfg.Vec3 space_ori = 1;
    if (has_space_ori()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->space_ori());
    }

    // required .gamer.cfg.Vec3 space_size = 2;
    if (has_space_size()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->space_size());
    }

    // required .gamer.cfg.Vec3 space_box_num = 3;
    if (has_space_box_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->space_box_num());
    }

    // required .gamer.cfg.Vec3 space_cell_num = 4;
    if (has_space_cell_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->space_cell_num());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SpaceCfg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SpaceCfg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SpaceCfg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SpaceCfg::MergeFrom(const SpaceCfg& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_space_ori()) {
      mutable_space_ori()->::gamer::cfg::Vec3::MergeFrom(from.space_ori());
    }
    if (from.has_space_size()) {
      mutable_space_size()->::gamer::cfg::Vec3::MergeFrom(from.space_size());
    }
    if (from.has_space_box_num()) {
      mutable_space_box_num()->::gamer::cfg::Vec3::MergeFrom(from.space_box_num());
    }
    if (from.has_space_cell_num()) {
      mutable_space_cell_num()->::gamer::cfg::Vec3::MergeFrom(from.space_cell_num());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SpaceCfg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpaceCfg::CopyFrom(const SpaceCfg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpaceCfg::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  if (has_space_ori()) {
    if (!this->space_ori().IsInitialized()) return false;
  }
  if (has_space_size()) {
    if (!this->space_size().IsInitialized()) return false;
  }
  if (has_space_box_num()) {
    if (!this->space_box_num().IsInitialized()) return false;
  }
  if (has_space_cell_num()) {
    if (!this->space_cell_num().IsInitialized()) return false;
  }
  return true;
}

void SpaceCfg::Swap(SpaceCfg* other) {
  if (other != this) {
    std::swap(space_ori_, other->space_ori_);
    std::swap(space_size_, other->space_size_);
    std::swap(space_box_num_, other->space_box_num_);
    std::swap(space_cell_num_, other->space_cell_num_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SpaceCfg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SpaceCfg_descriptor_;
  metadata.reflection = SpaceCfg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cfg
}  // namespace gamer

// @@protoc_insertion_point(global_scope)
